app:
  env: development
  port: 3000
  
database:
  host: localhost
  port: 27017
  # user: dev_user
  # pass: dev_pass
  name: nestdb

mail:
  user: dev@gmail.com
  pass: devpassword
redis:
  host: 127.0.0.1
  port: 6379
